"use client";

import { useRef } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Download, FileQuestion, FileText, Upload } from "lucide-react";
import { toast } from "sonner";
import { Button, buttonVariants } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import { fetchJson, retryServerErrors } from "@/lib/fetch-json";
import { formatFileSize, uploadProblem } from "@/lib/files/limits";
import { previewKind } from "@/lib/files/scope";

/** The least a list needs to hand over for a file to be previewed. */
export type PreviewFile = { id: string; fileName: string; fileType?: string | null; fileSize?: number | null };

type Meta = { id: string; fileName: string; fileType: string; fileSize: number; missing: boolean; generated: boolean; canEdit: boolean };

/**
 * One preview for every file in the app: an image in place, a PDF in a frame,
 * anything else a download — and, when the stored data is gone, a plain
 * statement of that with "Upload again" instead of an error page in a new tab.
 *
 * `files` is the list the person was looking at, so they can step through it.
 */
export function FilePreviewDialog({
  files,
  index,
  onIndexChange,
  onChanged,
}: {
  files: readonly PreviewFile[];
  /** Which file is open; null closes the dialog. */
  index: number | null;
  onIndexChange: (index: number | null) => void;
  /** Called after "Upload again" succeeds, to refresh the list behind. */
  onChanged?: () => void;
}) {
  const file = index === null ? null : (files[index] ?? null);
  return (
    <Dialog open={Boolean(file)} onOpenChange={(open) => !open && onIndexChange(null)}>
      <DialogContent className="flex max-h-[92vh] flex-col gap-3 sm:max-w-4xl">
        {file && index !== null && (
          <Preview key={file.id} file={file} position={files.length > 1 ? `${index + 1} of ${files.length}` : null} onPrev={index > 0 ? () => onIndexChange(index - 1) : undefined} onNext={index < files.length - 1 ? () => onIndexChange(index + 1) : undefined} onChanged={onChanged} />
        )}
      </DialogContent>
    </Dialog>
  );
}

function Preview({ file, position, onPrev, onNext, onChanged }: { file: PreviewFile; position: string | null; onPrev?: () => void; onNext?: () => void; onChanged?: () => void }) {
  const qc = useQueryClient();
  const input = useRef<HTMLInputElement>(null);
  const meta = useQuery<Meta>({
    queryKey: ["file-meta", file.id],
    queryFn: () => fetchJson(`/api/files/${file.id}?meta=1`),
    retry: retryServerErrors,
  });

  const replace = useMutation({
    mutationFn: (picked: File) => {
      const form = new FormData();
      form.set("file", picked);
      return fetchJson(`/api/files/${file.id}/replace`, { method: "POST", body: form });
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["file-meta", file.id] });
      onChanged?.();
      toast.success("File uploaded again");
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const m = meta.data;
  const name = m?.fileName ?? file.fileName;
  const url = `/api/files/${file.id}`;
  const kind = previewKind(m?.fileType ?? file.fileType);

  return (
    <>
      <DialogHeader>
        <DialogTitle className="truncate pr-8 text-base">{name}</DialogTitle>
        <DialogDescription>
          {[position, m ? formatFileSize(m.fileSize) : file.fileSize ? formatFileSize(file.fileSize) : null].filter(Boolean).join(" · ") || "File"}
        </DialogDescription>
      </DialogHeader>

      <div className="relative min-h-[16rem] flex-1 overflow-hidden rounded-md border bg-gray-50">
        {meta.isLoading ? (
          <Skeleton className="h-[60vh] w-full" />
        ) : meta.isError ? (
          <Notice icon={FileQuestion} title="This file could not be opened" body={(meta.error as Error).message} />
        ) : m?.missing ? (
          <Notice
            icon={FileQuestion}
            title="This file is missing"
            body={
              m.generated
                ? "The record is kept, but the stored document is gone. It was generated by the CRM; generate it again from where it was made."
                : m.canEdit
                  ? "The record is kept, but the stored file is gone. If you have the original, upload it again and it will sit on this same record."
                  : "The record is kept, but the stored file is gone. Ask the office to upload it again."
            }
            action={
              m.canEdit && !m.generated ? (
                <>
                  <input
                    ref={input}
                    type="file"
                    className="hidden"
                    onChange={(e) => {
                      const picked = e.target.files?.[0];
                      e.target.value = "";
                      if (!picked) return;
                      const problem = uploadProblem(picked);
                      if (problem) return void toast.error(problem);
                      replace.mutate(picked);
                    }}
                  />
                  <Button onClick={() => input.current?.click()} disabled={replace.isPending}>
                    <Upload className="mr-2 size-4" />
                    {replace.isPending ? "Uploading…" : "Upload again"}
                  </Button>
                </>
              ) : undefined
            }
          />
        ) : kind === "image" ? (
          // eslint-disable-next-line @next/next/no-img-element -- an authenticated, uncached API response, not a static asset
          <img src={url} alt={name} className="mx-auto max-h-[70vh] w-auto object-contain" />
        ) : kind === "pdf" ? (
          <>
            <iframe src={`${url}#toolbar=1`} title={name} className="hidden h-[70vh] w-full sm:block" />
            <div className="sm:hidden">
              <Notice icon={FileText} title="PDF document" body="Open it to read it on this device." action={<OpenButton url={url} />} />
            </div>
          </>
        ) : (
          <Notice icon={FileText} title="No preview for this kind of file" body="Download it to open it." action={<DownloadButton url={url} />} />
        )}

        {onPrev && (
          <Button size="icon" variant="secondary" className="absolute left-2 top-1/2 size-8 -translate-y-1/2 rounded-full shadow" aria-label="Previous file" onClick={onPrev}>
            <ChevronLeft className="size-4" />
          </Button>
        )}
        {onNext && (
          <Button size="icon" variant="secondary" className="absolute right-2 top-1/2 size-8 -translate-y-1/2 rounded-full shadow" aria-label="Next file" onClick={onNext}>
            <ChevronRight className="size-4" />
          </Button>
        )}
      </div>

      {/* A file with no preview already offers its download in the middle of the dialog. */}
      {m && !m.missing && kind !== "other" && (
        <div className="flex flex-wrap justify-end gap-2">
          <OpenButton url={url} variant="outline" />
          <DownloadButton url={url} />
        </div>
      )}
    </>
  );
}

function OpenButton({ url, variant = "default" }: { url: string; variant?: "default" | "outline" }) {
  // Plain links styled as buttons: they navigate, they are not buttons.
  return (
    <a href={url} target="_blank" rel="noreferrer" className={buttonVariants({ variant, size: "sm" })}>
      Open in a new tab
    </a>
  );
}

function DownloadButton({ url }: { url: string }) {
  return (
    <a href={`${url}?download=1`} className={buttonVariants({ variant: "outline", size: "sm" })}>
      <Download className="mr-1.5 size-4" />
      Download
    </a>
  );
}

function Notice({ icon: Icon, title, body, action }: { icon: typeof FileText; title: string; body?: string; action?: React.ReactNode }) {
  return (
    <div className="flex min-h-[16rem] flex-col items-center justify-center gap-2 px-6 py-10 text-center">
      <span className="inline-flex size-10 items-center justify-center rounded-full bg-gray-200 text-gray-600">
        <Icon className="size-5" />
      </span>
      <p className="text-sm font-medium text-gray-900">{title}</p>
      {body && <p className="max-w-md text-sm text-muted-foreground">{body}</p>}
      {action && <div className="mt-2">{action}</div>}
    </div>
  );
}
