import { defineTemplate } from "../../../src/lib/workflows/templates/define";
import { LEGAL_NO_PERMIT_WARNING, PHASE_BANDS as B } from "../../../src/lib/workflows/templates/types";
import { ACC, EST, NO_PERMIT_TASKS, OA, PC, PM, PUR, QC, REQ, SR, SUP, any, task, when } from "./_shorthand";

/** Exterior openings of any kind. */
const EXT = any("windows", "exterior_doors", "storefront");

export const DOORS_WINDOWS = defineTemplate({
  key: "doors_windows",
  name: "Doors & Windows",
  kind: "TRADE",
  trade: "Doors & Windows",
  serviceCategoryNames: ["Windows", "Doors"],
  description: "Window and door replacement: measurement, product approvals, permitting, ordering, installation and closeout.",
  scopeToggles: [
    { key: "windows", label: "Windows", default: true },
    { key: "exterior_doors", label: "Exterior doors", default: true },
    { key: "interior_doors", label: "Interior doors", default: false },
    { key: "storefront", label: "Storefront", default: false },
    { key: "impact", label: "Impact products", default: true },
    { key: "non_impact", label: "Non-impact products", default: false },
    { key: "interior_restoration", label: "Interior restoration", default: true },
    { key: "exterior_restoration", label: "Exterior restoration", default: true },
    { key: "engineering", label: "Engineering required", default: false },
  ],
  phases: [
    {
      key: "scope_review",
      name: "Doors & Windows Scope Review",
      band: B.SCOPE_REVIEW,
      startsAfter: ["core:review_contract"],
      tasks: [
        task("verify_opening_count", "Verify opening count", EST, 1, { requiredEvidence: "ATTACHMENT" }),
        task("verify_field_measurements", "Verify field measurements", EST, 2, { dependsOn: ["^"], blocking: true, requiredEvidence: "ATTACHMENT" }),
        task("confirm_window_door_types", "Confirm window and door types", EST, 1, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("confirm_impact_requirements", "Confirm impact or non-impact requirements", EST, 0, {
          dependsOn: ["^"],
          priority: "HIGH",
          condition: EXT,
          checklist: [
            "HVHZ / wind-borne debris zone determined",
            when("impact", "Impact-rated products specified"),
            when("non_impact", "Shutters or non-impact products allowed"),
          ],
        }),
        task("confirm_design_pressures", "Confirm design pressures", EST, 1, {
          dependsOn: ["^"],
          requiredEvidence: "ATTACHMENT",
          condition: EXT,
          checklist: ["Design pressure per opening", when("engineering", "Site-specific engineering ordered")],
        }),
        task("confirm_egress_requirements", "Confirm egress requirements", EST, 0, { dependsOn: ["confirm_window_door_types"], condition: any("windows") }),
        task("confirm_energy_requirements", "Confirm energy requirements", EST, 0, { dependsOn: ["confirm_window_door_types"], condition: EXT }),
        task("confirm_product_colors_finishes", "Confirm product colors and finishes", SR, 1, {
          dependsOn: ["confirm_window_door_types"],
          requiredEvidence: "ATTACHMENT",
        }),
        task("confirm_frame_glass_hardware", "Confirm frame, glass and hardware selections", SR, 1, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("confirm_restoration_scope", "Confirm interior and exterior restoration scope", PM, 1, {
          dependsOn: ["confirm_window_door_types"],
          condition: any("interior_restoration", "exterior_restoration"),
        }),
        task("photograph_existing_openings", "Photograph existing openings", SUP, 1, { dependsOn: ["verify_opening_count"], requiredEvidence: "PHOTO" }),
        task("obtain_owner_approval_order_specs", "Obtain owner approval of final order specifications", SR, 2, {
          dependsOn: [
            "confirm_design_pressures",
            "confirm_frame_glass_hardware",
            "confirm_restoration_scope",
            "confirm_egress_requirements",
            "confirm_energy_requirements",
          ],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "ATTACHMENT",
        }),
      ],
    },
    {
      key: "permit_required",
      name: "Doors & Windows Permit",
      band: B.PERMITTING,
      permit: "REQUIRED",
      startsAfter: ["core:determine_permit_requirement"],
      tasks: [
        task("prepare_permit_application", "Prepare permit application", PC, 1, { requiredEvidence: "ATTACHMENT" }),
        task("confirm_owner_authorization", "Confirm owner authorization", PC, 1, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("prepare_notice_of_commencement", "Prepare or record Notice of Commencement", PC, 2, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("gather_product_approvals", "Gather applicable Miami-Dade NOAs or Florida Product Approvals", PC, 2, {
          dependsOn: ["confirm_window_door_types"],
          requiredEvidence: "ATTACHMENT",
          condition: EXT,
        }),
        task("prepare_opening_schedule", "Prepare opening schedule", PC, 2, {
          dependsOn: ["verify_field_measurements", "confirm_window_door_types"],
          requiredEvidence: "ATTACHMENT",
        }),
        task("confirm_dp_documentation", "Confirm design-pressure documentation", PC, 1, {
          dependsOn: ["^", "confirm_design_pressures"],
          requiredEvidence: "ATTACHMENT",
          condition: EXT,
          checklist: [when("engineering", "Signed and sealed calculations attached")],
        }),
        task("submit_permit_package", "Submit permit package", PC, 1, {
          dependsOn: [
            "prepare_permit_application",
            "confirm_owner_authorization",
            "prepare_notice_of_commencement",
            "gather_product_approvals",
            "prepare_opening_schedule",
            "confirm_dp_documentation",
          ],
          priority: "HIGH",
          requiredEvidence: "ATTACHMENT",
        }),
        task("track_plan_review", "Track plan review", PC, 5, { dependsOn: ["^"] }),
        task("respond_to_permit_comments", "Respond to permit comments", PC, 3, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("confirm_permit_issued", "Confirm permit issued", PC, 5, {
          dependsOn: ["^"],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "PERMIT_NUMBER",
          description: "Record the permit number on the job's Permits tab; this step cannot be completed without it.",
        }),
        task("upload_approved_permit_documents", "Upload approved permit documents", PC, 1, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("post_permit_approved_documents", "Post permit and approved documents", SUP, 1, {
          dependsOn: ["confirm_permit_issued"],
          requiredEvidence: "PHOTO",
        }),
        task("confirm_inspection_requirements", "Confirm inspection requirements", PC, 1, {
          dependsOn: ["confirm_permit_issued"],
          checklist: ["In-progress / buck inspection", "Final inspection", "Label verification"],
        }),
      ],
    },
    {
      key: "no_permit",
      name: "No Permit Required",
      band: B.PERMITTING,
      permit: "NOT_REQUIRED",
      note: LEGAL_NO_PERMIT_WARNING,
      startsAfter: ["core:determine_permit_requirement"],
      tasks: NO_PERMIT_TASKS("Verify and document that the door or window work does not require a permit"),
    },
    {
      key: "procurement",
      name: "Doors & Windows Procurement",
      band: B.PROCUREMENT,
      startsAfter: ["obtain_owner_approval_order_specs"],
      tasks: [
        task("confirm_final_field_measurements", "Confirm final field measurements", EST, 1, { blocking: true, requiredEvidence: "ATTACHMENT" }),
        task("obtain_signed_product_selection", "Obtain signed product-selection approval", SR, 1, {
          dependsOn: ["^"],
          blocking: true,
          requiredEvidence: "ATTACHMENT",
        }),
        task("confirm_product_approval_numbers", "Confirm product approval numbers", PUR, 1, {
          dependsOn: ["^"],
          requiredEvidence: "ATTACHMENT",
          condition: EXT,
        }),
        task("place_material_order", "Place material order", PUR, 1, {
          dependsOn: ["^", "obtain_owner_approval_order_specs", "core:verify_deposit"],
          priority: "HIGH",
          requiredEvidence: "ATTACHMENT",
        }),
        task("upload_purchase_order", "Upload purchase order", PUR, 0, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("confirm_manufacturer_acknowledgment", "Confirm manufacturer acknowledgment", PUR, 3, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("confirm_production_lead_time", "Confirm production lead time", PUR, 1, { dependsOn: ["^"] }),
        task("track_manufacturing_status", "Track manufacturing status", PUR, 10, { dependsOn: ["^"] }),
        task("confirm_delivery_date", "Confirm delivery date", PUR, 2, { dependsOn: ["^"] }),
        task("inspect_delivered_products", "Inspect delivered products for damage and accuracy", SUP, 1, {
          dependsOn: ["^"],
          priority: "HIGH",
          requiredEvidence: "PHOTO",
        }),
        task("document_serial_numbers_labels", "Document serial numbers and labels where applicable", SUP, 0, {
          dependsOn: ["^"],
          requiredEvidence: "PHOTO",
          condition: any("impact"),
        }),
        task("schedule_installation", "Schedule installation", PM, 1, { dependsOn: ["inspect_delivered_products"] }),
      ],
    },
    {
      key: "production_readiness",
      name: "Doors & Windows Production Readiness",
      band: B.PRODUCTION_READINESS,
      startsAfter: ["confirm_delivery_date"],
      tasks: [
        task("assign_installation_crew", "Assign installation crew", PM, 1, { blocking: true }),
        task("confirm_site_access", "Confirm site access", SUP, 1, { dependsOn: ["^"] }),
        task("confirm_protection_occupied_areas", "Confirm protection of occupied areas", SUP, 0, { dependsOn: ["^"] }),
        task("confirm_equipment_staging", "Confirm equipment and staging requirements", SUP, 0, {
          dependsOn: ["^"],
          checklist: [when("storefront", "Lift / scaffold"), "Glazing suction equipment"],
        }),
        task("confirm_weather_conditions", "Confirm weather conditions", SUP, 1, { dependsOn: ["^"] }),
        task("confirm_inspection_sequence", "Confirm inspection sequence", PC, 1, { dependsOn: ["assign_installation_crew"], condition: REQ }),
        task("notify_customer_installation_date", "Notify customer of installation date", PM, 1, {
          dependsOn: ["confirm_weather_conditions", "schedule_installation"],
        }),
        task("confirm_disposal_plan", "Confirm disposal plan", SUP, 0, { dependsOn: ["confirm_equipment_staging"] }),
        task("confirm_installation_materials_fasteners", "Confirm installation materials and fasteners", PUR, 1, {
          dependsOn: ["assign_installation_crew"],
          checklist: ["Anchors per NOA", "Sealant", "Shims", "Flashing tape"],
        }),
        task("confirm_docs_onsite", "Confirm approved plans and product documentation are available onsite", SUP, 1, {
          dependsOn: ["^"],
          requiredEvidence: "ATTACHMENT",
        }),
      ],
    },
    {
      key: "installation",
      name: "Doors & Windows Installation",
      band: B.INSTALLATION,
      tasks: [
        task("photograph_pre_installation", "Photograph pre-installation conditions", SUP, 0, {
          dependsOn: [
            "confirm_permit_issued",
            "obtain_pm_approval_no_permit",
            "notify_customer_installation_date",
            "confirm_docs_onsite",
            "core:confirm_production_start",
          ],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "PHOTO",
        }),
        task("protect_adjacent_finishes", "Protect adjacent finishes", SUP, 0, { dependsOn: ["^"], requiredEvidence: "PHOTO" }),
        task("remove_existing_products", "Remove existing products", SUP, 0, { dependsOn: ["^"], requiredEvidence: "PHOTO" }),
        task("inspect_rough_openings", "Inspect rough openings", SUP, 0, { dependsOn: ["^"], requiredEvidence: "PHOTO" }),
        task("document_concealed_damage", "Document concealed damage", SUP, 0, { dependsOn: ["^"], requiredEvidence: "PHOTO" }),
        task("create_co_additional_repairs", "Create change order for additional repairs if required", PM, 1, {
          dependsOn: ["^"],
          requiredEvidence: "ATTACHMENT",
          description: "Skip when no concealed damage was found.",
        }),
        task("prepare_openings", "Prepare openings", SUP, 1, { dependsOn: ["^"], requiredEvidence: "PHOTO" }),
        task("install_windows_doors", "Install windows and doors", SUP, 2, { dependsOn: ["^"], requiredEvidence: "PHOTO" }),
        task("install_anchors_fasteners", "Install approved anchors and fasteners", SUP, 0, {
          dependsOn: ["^"],
          requiredEvidence: "PHOTO",
          checklist: ["Per NOA schedule", "Embedment", "Spacing"],
        }),
        task("complete_flashing_waterproofing", "Complete flashing and waterproofing", SUP, 1, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: EXT }),
        task("complete_sealants", "Complete sealants", SUP, 0, { dependsOn: ["^"], requiredEvidence: "PHOTO" }),
        task("obtain_in_progress_inspection", "Obtain in-progress inspection if required", PC, 1, {
          dependsOn: ["^"],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "INSPECTION_RESULT",
          condition: REQ,
        }),
        task("complete_restoration", "Complete interior and exterior restoration", SUP, 2, {
          dependsOn: ["^"],
          requiredEvidence: "PHOTO",
          condition: any("interior_restoration", "exterior_restoration"),
        }),
        task("install_hardware_screens", "Install hardware and screens", SUP, 1, { dependsOn: ["^"], requiredEvidence: "PHOTO" }),
        task("test_operation_locking", "Test operation and locking", SUP, 0, { dependsOn: ["^"] }),
        task("verify_labels_available", "Verify labels remain available for inspection", SUP, 0, {
          dependsOn: ["^"],
          priority: "HIGH",
          requiredEvidence: "PHOTO",
          condition: REQ,
        }),
        task("complete_daily_reports_photos", "Complete daily reports and photographs", SUP, 0, {
          dependsOn: ["photograph_pre_installation"],
          requiredEvidence: "PHOTO",
          description: "Ongoing through installation.",
        }),
        task("perform_internal_quality_inspection", "Perform internal quality inspection", QC, 1, {
          dependsOn: ["test_operation_locking"],
          requiredEvidence: "PHOTO",
          overridesCoreKey: "internal_quality_inspection",
        }),
      ],
    },
    {
      key: "closeout",
      name: "Doors & Windows Closeout",
      band: B.TRADE_CLOSEOUT,
      startsAfter: ["perform_internal_quality_inspection"],
      tasks: [
        task("complete_installation_punch_list", "Complete installation punch list", SUP, 2, {
          dependsOn: ["core:create_punch_list"],
          requiredEvidence: "PHOTO",
          overridesCoreKey: "complete_punch_list",
        }),
        task("request_final_inspection", "Request final inspection if required", PC, 1, {
          dependsOn: ["^"],
          priority: "HIGH",
          condition: REQ,
          overridesCoreKey: "obtain_final_inspection",
        }),
        task("record_final_inspection_result", "Record final inspection result", PC, 3, {
          dependsOn: ["^"],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "INSPECTION_RESULT",
          condition: REQ,
        }),
        task("create_correction_tasks_failed", "Create correction tasks for failed inspection items", PM, 1, {
          dependsOn: ["^"],
          condition: REQ,
          description: "Skip when the inspection passed first time.",
        }),
        task("obtain_final_approval", "Obtain final approval", PM, 1, { dependsOn: ["^"], blocking: true, priority: "HIGH" }),
        task("register_manufacturer_warranties", "Register manufacturer warranties", OA, 3, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("deliver_warranty_operation_info", "Deliver warranty and operation information", OA, 1, {
          dependsOn: ["^"],
          requiredEvidence: "ATTACHMENT",
          overridesCoreKey: "deliver_warranty_documents",
        }),
        task("collect_sub_supplier_releases", "Collect subcontractor and supplier releases", ACC, 3, {
          dependsOn: ["obtain_final_approval"],
          requiredEvidence: "ATTACHMENT",
          overridesCoreKey: "collect_lien_releases",
        }),
        task("complete_final_cleaning", "Complete final cleaning", SUP, 1, { dependsOn: ["obtain_final_approval"], requiredEvidence: "PHOTO" }),
        task("submit_final_invoice", "Submit final invoice", ACC, 1, {
          dependsOn: ["obtain_final_approval", "complete_final_cleaning"],
          priority: "HIGH",
          requiredEvidence: "ATTACHMENT",
          overridesCoreKey: "submit_final_invoice",
        }),
        task("confirm_final_payment", "Confirm final payment", ACC, 5, {
          dependsOn: ["^"],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "PAYMENT_STATUS",
          requiredEvidenceParam: "FINAL",
          overridesCoreKey: "confirm_final_payment",
        }),
        task("close_doors_windows_workflow", "Close doors and windows workflow", PM, 1, {
          dependsOn: ["^", "deliver_warranty_operation_info", "collect_sub_supplier_releases"],
          overridesCoreKey: "close_job",
        }),
      ],
    },
  ],
});
