import { defineTemplate } from "../../../src/lib/workflows/templates/define";
import { LEGAL_NO_PERMIT_WARNING, PHASE_BANDS as B } from "../../../src/lib/workflows/templates/types";
import { ACC, EST, NO_PERMIT_TASKS, OA, PC, PM, PUR, QC, REQ, SR, SUP, any, task } from "./_shorthand";

export const INTERIOR_RENOVATION = defineTemplate({
  key: "interior_renovation",
  name: "Interior Renovation",
  kind: "TRADE",
  trade: "Interior Renovation",
  serviceCategoryNames: ["Interior Renovations", "Drywall"],
  description: "Kitchens, baths, drywall and general interior work, with each trade discipline as an optional scope.",
  scopeToggles: [
    { key: "demolition", label: "Demolition", default: true },
    { key: "framing", label: "Framing", default: false },
    { key: "drywall", label: "Drywall", default: true },
    { key: "painting", label: "Painting", default: true },
    { key: "flooring", label: "Flooring", default: true },
    { key: "cabinets", label: "Cabinets and countertops", default: false },
    { key: "plumbing", label: "Plumbing", default: false },
    { key: "electrical", label: "Electrical", default: false },
    { key: "hvac", label: "HVAC", default: false },
    { key: "fire_protection", label: "Fire protection", default: false },
    { key: "doors_trim", label: "Doors and trim", default: true },
  ],
  phases: [
    {
      key: "scope_review",
      name: "Interior Scope Review",
      band: B.SCOPE_REVIEW,
      startsAfter: ["core:review_contract"],
      tasks: [
        task("verify_plans_scope", "Verify plans and scope", PM, 1, { blocking: true, requiredEvidence: "ATTACHMENT" }),
        task("confirm_demolition_limits", "Confirm demolition limits", PM, 1, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT", condition: any("demolition") }),
        task("confirm_room_by_room_scope", "Confirm room-by-room scope", PM, 1, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("confirm_finish_selections", "Confirm finish selections", SR, 2, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("confirm_structural_work", "Confirm structural work", EST, 1, {
          dependsOn: ["confirm_room_by_room_scope"],
          requiredEvidence: "ATTACHMENT",
          condition: any("framing"),
          checklist: ["Load-bearing walls identified", "Engineer letter obtained"],
        }),
        task("confirm_electrical_work", "Confirm electrical work", EST, 1, { dependsOn: ["confirm_room_by_room_scope"], condition: any("electrical") }),
        task("confirm_plumbing_work", "Confirm plumbing work", EST, 1, { dependsOn: ["confirm_room_by_room_scope"], condition: any("plumbing") }),
        task("confirm_hvac_work", "Confirm HVAC work", EST, 1, { dependsOn: ["confirm_room_by_room_scope"], condition: any("hvac") }),
        task("confirm_fire_protection_requirements", "Confirm fire-protection requirements", EST, 1, {
          dependsOn: ["confirm_room_by_room_scope"],
          priority: "HIGH",
          condition: any("fire_protection"),
        }),
        task("confirm_accessibility_requirements", "Confirm accessibility requirements", PM, 1, { dependsOn: ["confirm_room_by_room_scope"] }),
        task("confirm_occupied_building_restrictions", "Confirm occupied-building restrictions", SUP, 1, { dependsOn: ["confirm_room_by_room_scope"] }),
        task("photograph_existing_conditions", "Photograph existing conditions", SUP, 1, { dependsOn: ["verify_plans_scope"], requiredEvidence: "PHOTO" }),
      ],
    },
    {
      key: "permit_required",
      name: "Interior Permit",
      band: B.PERMITTING,
      permit: "REQUIRED",
      startsAfter: ["core:determine_permit_requirement"],
      tasks: [
        task("confirm_permit_disciplines", "Confirm required permit disciplines", PC, 1, {
          checklist: ["Building", "Electrical", "Plumbing", "Mechanical", "Fire"],
        }),
        task("obtain_owner_authorization", "Obtain owner authorization", PC, 1, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("prepare_notice_of_commencement", "Prepare or record Notice of Commencement", PC, 2, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("gather_arch_eng_plans", "Gather architectural and engineering plans", PC, 3, { dependsOn: ["confirm_permit_disciplines"], requiredEvidence: "ATTACHMENT" }),
        task("gather_product_approvals", "Gather product approvals where applicable", PC, 2, { dependsOn: ["confirm_permit_disciplines"], requiredEvidence: "ATTACHMENT" }),
        task("submit_permit_application", "Submit permit application", PC, 1, {
          dependsOn: ["obtain_owner_authorization", "prepare_notice_of_commencement", "gather_arch_eng_plans", "gather_product_approvals"],
          priority: "HIGH",
          requiredEvidence: "ATTACHMENT",
        }),
        task("track_plan_review", "Track plan review", PC, 5, { dependsOn: ["^"] }),
        task("respond_to_permit_comments", "Respond to permit comments", PC, 3, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("confirm_permit_issued", "Confirm permit issued", PC, 5, {
          dependsOn: ["^"],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "PERMIT_NUMBER",
          description: "Record the permit number on the job's Permits tab; this step cannot be completed without it.",
        }),
        task("upload_approved_plans", "Upload approved plans", PC, 1, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("post_permit_approved_plans", "Post permit and approved plans", SUP, 1, { dependsOn: ["confirm_permit_issued"], requiredEvidence: "PHOTO" }),
        task("create_inspection_schedule_by_discipline", "Create inspection schedule by discipline", PC, 1, {
          dependsOn: ["confirm_permit_issued"],
          requiredEvidence: "ATTACHMENT",
        }),
      ],
    },
    {
      key: "no_permit",
      name: "No Permit Required",
      band: B.PERMITTING,
      permit: "NOT_REQUIRED",
      note: LEGAL_NO_PERMIT_WARNING,
      startsAfter: ["core:determine_permit_requirement"],
      tasks: NO_PERMIT_TASKS("Verify and document that the interior work does not require a permit"),
    },
    {
      key: "procurement",
      name: "Interior Procurement",
      band: B.PROCUREMENT,
      startsAfter: ["confirm_finish_selections"],
      tasks: [
        task("confirm_finish_schedule", "Confirm finish schedule", PM, 1, { requiredEvidence: "ATTACHMENT" }),
        task("confirm_long_lead_items", "Confirm long-lead items", PUR, 1, { dependsOn: ["^"] }),
        task("obtain_subcontractor_proposals", "Obtain subcontractor proposals", PM, 3, { dependsOn: ["confirm_finish_schedule"], requiredEvidence: "ATTACHMENT" }),
        task("issue_pos_and_subcontracts", "Issue purchase orders and subcontracts", PUR, 2, {
          dependsOn: ["confirm_long_lead_items", "obtain_subcontractor_proposals", "core:verify_deposit"],
          priority: "HIGH",
          requiredEvidence: "ATTACHMENT",
        }),
        task("confirm_cabinets_countertops", "Confirm cabinets and countertops", PUR, 1, {
          dependsOn: ["issue_pos_and_subcontracts"],
          requiredEvidence: "ATTACHMENT",
          condition: any("cabinets"),
        }),
        task("confirm_doors_hardware", "Confirm doors and hardware", PUR, 1, { dependsOn: ["issue_pos_and_subcontracts"], condition: any("doors_trim") }),
        task("confirm_plumbing_fixtures", "Confirm plumbing fixtures", PUR, 1, { dependsOn: ["issue_pos_and_subcontracts"], condition: any("plumbing") }),
        task("confirm_electrical_fixtures", "Confirm electrical fixtures", PUR, 1, { dependsOn: ["issue_pos_and_subcontracts"], condition: any("electrical") }),
        task("confirm_flooring", "Confirm flooring", PUR, 1, { dependsOn: ["issue_pos_and_subcontracts"], condition: any("flooring") }),
        task("confirm_paint_colors", "Confirm paint colors", SR, 1, {
          dependsOn: ["confirm_finish_schedule"],
          requiredEvidence: "ATTACHMENT",
          condition: any("painting"),
        }),
        task("establish_delivery_schedule", "Establish delivery schedule", PUR, 2, { dependsOn: ["confirm_long_lead_items", "issue_pos_and_subcontracts"] }),
        task("confirm_material_storage_location", "Confirm material storage location", SUP, 1, { dependsOn: ["^"] }),
      ],
    },
    {
      key: "production_readiness",
      name: "Interior Production Readiness",
      band: B.PRODUCTION_READINESS,
      startsAfter: ["issue_pos_and_subcontracts"],
      tasks: [
        task("assign_pm_and_superintendent", "Assign project manager and superintendent", PM, 1, {
          blocking: true,
          description: "Fill the Project manager and Superintendent slots on the Workflow tab's team card.",
        }),
        task("conduct_precon_meeting", "Conduct preconstruction meeting", PM, 2, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
        task("confirm_access_working_hours", "Confirm access and working hours", SUP, 1, { dependsOn: ["^"] }),
        task("confirm_dust_occupied_protection", "Confirm dust and occupied-space protection", SUP, 1, { dependsOn: ["^"] }),
        task("confirm_temporary_utilities", "Confirm temporary utilities", SUP, 1, { dependsOn: ["conduct_precon_meeting"] }),
        task("confirm_dumpster_debris_plan", "Confirm dumpster and debris-removal plan", SUP, 1, { dependsOn: ["conduct_precon_meeting"] }),
        task("confirm_safety_plan", "Confirm safety plan", SUP, 1, {
          dependsOn: ["conduct_precon_meeting"],
          priority: "URGENT",
          blocking: true,
          requiredEvidence: "ATTACHMENT",
        }),
        task("confirm_inspection_sequence", "Confirm inspection sequence", PC, 1, { dependsOn: ["conduct_precon_meeting"], condition: REQ }),
        task("notify_customer_start_date", "Notify customer of start date", PM, 1, { dependsOn: ["confirm_safety_plan"] }),
        task("establish_baseline_schedule", "Establish baseline schedule", PM, 1, { dependsOn: ["^"], requiredEvidence: "ATTACHMENT" }),
      ],
    },
    {
      key: "construction",
      name: "Interior Construction",
      band: B.INSTALLATION,
      tasks: [
        task("mobilize_install_protection", "Mobilize and install protection", SUP, 0, {
          dependsOn: [
            "confirm_permit_issued",
            "obtain_pm_approval_no_permit",
            "confirm_safety_plan",
            "establish_baseline_schedule",
            "core:confirm_production_start",
          ],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "PHOTO",
        }),
        task("complete_demolition", "Complete demolition", SUP, 2, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("demolition") }),
        task("document_concealed_conditions", "Document concealed conditions", SUP, 0, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("demolition") }),
        task("complete_structural_framing", "Complete structural framing", SUP, 3, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("framing") }),
        task("complete_plumbing_rough_in", "Complete plumbing rough-in", SUP, 2, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("plumbing") }),
        task("complete_electrical_rough_in", "Complete electrical rough-in", SUP, 2, {
          dependsOn: ["complete_structural_framing"],
          requiredEvidence: "PHOTO",
          condition: any("electrical"),
        }),
        task("complete_hvac_rough_in", "Complete HVAC rough-in", SUP, 2, {
          dependsOn: ["complete_structural_framing"],
          requiredEvidence: "PHOTO",
          condition: any("hvac"),
        }),
        task("complete_fire_protection_rough_in", "Complete fire-protection rough-in", SUP, 2, {
          dependsOn: ["complete_structural_framing"],
          requiredEvidence: "PHOTO",
          condition: any("fire_protection"),
        }),
        task("obtain_rough_inspections", "Obtain rough inspections if required", PC, 2, {
          dependsOn: [
            "complete_structural_framing",
            "complete_plumbing_rough_in",
            "complete_electrical_rough_in",
            "complete_hvac_rough_in",
            "complete_fire_protection_rough_in",
          ],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "INSPECTION_RESULT",
          condition: { ...REQ, ...any("framing", "plumbing", "electrical", "hvac", "fire_protection") },
        }),
        task("install_insulation", "Install insulation", SUP, 1, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("framing") }),
        task("obtain_insulation_inspection", "Obtain insulation inspection if required", PC, 1, {
          dependsOn: ["^"],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "INSPECTION_RESULT",
          condition: { ...REQ, ...any("framing") },
        }),
        task("install_drywall", "Install drywall", SUP, 3, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("drywall") }),
        task("complete_drywall_finishing", "Complete drywall finishing", SUP, 3, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("drywall") }),
        task("prime_and_paint", "Prime and paint", SUP, 3, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("painting") }),
        task("install_cabinets_countertops", "Install cabinets and countertops", SUP, 3, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("cabinets") }),
        task("install_flooring", "Install flooring", SUP, 3, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("flooring") }),
        task("install_doors_trim_hardware", "Install doors, trim and hardware", SUP, 2, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("doors_trim") }),
        task("complete_plumbing_trim_out", "Complete plumbing trim-out", SUP, 1, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("plumbing") }),
        task("complete_electrical_trim_out", "Complete electrical trim-out", SUP, 1, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("electrical") }),
        task("complete_hvac_trim_out", "Complete HVAC trim-out", SUP, 1, { dependsOn: ["^"], requiredEvidence: "PHOTO", condition: any("hvac") }),
        task("complete_final_finishes", "Complete final finishes", SUP, 2, { dependsOn: ["^"], requiredEvidence: "PHOTO" }),
        task("complete_daily_reports_photos", "Complete daily reports and photographs", SUP, 0, {
          dependsOn: ["mobilize_install_protection"],
          requiredEvidence: "PHOTO",
          description: "Ongoing through construction.",
        }),
        task("perform_internal_quality_review", "Perform internal quality review", QC, 1, {
          dependsOn: ["complete_final_finishes"],
          requiredEvidence: "PHOTO",
          overridesCoreKey: "internal_quality_inspection",
        }),
      ],
    },
    {
      key: "closeout",
      name: "Interior Closeout",
      band: B.TRADE_CLOSEOUT,
      startsAfter: ["perform_internal_quality_review"],
      tasks: [
        task("complete_trade_inspections", "Complete trade inspections", PC, 2, {
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "INSPECTION_RESULT",
          condition: { ...REQ, ...any("plumbing", "electrical", "hvac", "fire_protection") },
        }),
        task("request_final_building_inspection", "Request final building inspection if required", PC, 1, {
          dependsOn: ["^"],
          priority: "HIGH",
          condition: REQ,
          overridesCoreKey: "obtain_final_inspection",
        }),
        task("record_inspection_results", "Record inspection results", PC, 3, {
          dependsOn: ["^"],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "INSPECTION_RESULT",
          condition: REQ,
        }),
        task("create_correction_tasks_failed", "Create correction tasks for failed inspections", PM, 1, {
          dependsOn: ["^"],
          condition: REQ,
          description: "Skip when every inspection passed first time.",
        }),
        task("complete_internal_punch_list", "Complete internal punch list", SUP, 3, {
          dependsOn: ["core:create_punch_list", "create_correction_tasks_failed"],
          requiredEvidence: "PHOTO",
          overridesCoreKey: "complete_punch_list",
        }),
        task("complete_owner_punch_list", "Complete owner punch list", SUP, 3, { dependsOn: ["^"], requiredEvidence: "PHOTO" }),
        task("perform_final_cleaning", "Perform final cleaning", SUP, 1, { dependsOn: ["^"], requiredEvidence: "PHOTO" }),
        task("collect_warranties_manuals", "Collect warranties and operating manuals", OA, 3, {
          dependsOn: ["complete_owner_punch_list"],
          requiredEvidence: "ATTACHMENT",
          overridesCoreKey: "deliver_warranty_documents",
        }),
        task("collect_sub_supplier_releases", "Collect subcontractor and supplier releases", ACC, 3, {
          dependsOn: ["complete_owner_punch_list"],
          requiredEvidence: "ATTACHMENT",
          overridesCoreKey: "collect_lien_releases",
        }),
        task("submit_final_invoice", "Submit final invoice", ACC, 1, {
          dependsOn: ["perform_final_cleaning", "record_inspection_results"],
          priority: "HIGH",
          requiredEvidence: "ATTACHMENT",
          overridesCoreKey: "submit_final_invoice",
        }),
        task("confirm_final_payment", "Confirm final payment", ACC, 5, {
          dependsOn: ["^"],
          blocking: true,
          priority: "HIGH",
          requiredEvidence: "PAYMENT_STATUS",
          requiredEvidenceParam: "FINAL",
          overridesCoreKey: "confirm_final_payment",
        }),
        task("close_interior_workflow", "Close interior renovation workflow", PM, 1, {
          dependsOn: ["^", "collect_warranties_manuals", "collect_sub_supplier_releases"],
          overridesCoreKey: "close_job",
        }),
      ],
    },
  ],
});
